version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.26
    - 14.14.34
    - 14.14.36
    - 14.14.41
    - 15.0.0
  - dependency-name: "@octokit/types"
    versions:
    - 6.10.1
    - 6.11.2
    - 6.12.0
    - 6.12.1
    - 6.13.1
    - 6.13.2
    - 6.7.0
    - 6.7.1
    - 6.8.3
    - 6.9.0
  - dependency-name: typescript
    versions:
    - 4.1.4
