name: 'Initialize Pull Request'
description: 'JavaScript wrapper for GitHub Actions, runs `octokit.pulls.create` with provided Inputs'


inputs:
  pull_request_token:
    description: 'Secret authentication token with permissions to initialize Pull Requests for repository'
    required: true

  head:
    description: 'Where changes are implemented, eg. `your-name:feature-branch`'
    required: true

  base:
    description: 'Branch name where changes should be incorporated, eg. `master`'
    required: true

  title:
    description: 'Commit title, generally should be less than 74 characters'
    required: true

  body:
    description: 'Multi-line commit message describing changes'
    required: true

  maintainer_can_modify:
    description: 'When `undefined`, defaults to assuming `true`'
    required: false

  draft:
    description: '[Experimental] When `true`, no notifications are generated'
    required: false

  debug:
    description: '[Experimental] When `true`, output response data via `JSON.stringify`'
    required: false

  verbose:
    description: 'When `true`, output informative response data'
    required: false


outputs:
  html_url:
    description: 'URL that Pull Request may be reviewed at'

  number:
    description: 'Pull Request number'


runs:
  using: 'node12'
  main: 'index.js'


branding:
  icon: git-pull-request
  color: black
